# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  web:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build --if-present
    - name: Inspect code with eslint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
    - name: Run tests
      run: npm test
  
  server:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build --if-present
    - name: Inspect code with eslint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
    - name: Run tests
      run: npm test
